Wayland clipboard support via data_control protocol
ArturKovacs/arboard pull request #12
Opened 2021-04-03 09:09 UTC by xanderio

While it is true that wayland can support that X11 way of handling
clipboard support, this requires a running xwayland server and
compositor support for running xwayland.

This change introduces a new clipboard context
`WaylandDataControlClipboardContext` which is a wrapper around the
wl-clipboard-rs crate. This crate handles all of the communication with
the compositor for us.

To selected between X11 and wayland data_control clipboard handle is not
possible via a platform selector, as is the case for windows and mac,
two new features where add `x11` and `wayland-data-control`. The `x11`
feature is in the `default` feature set as to preserve backward
compatibility.

The feature name `wayland-data-control` was chosen to handle other
possible wayland protocols to interface with a clipboard.

Looking forward to your review :)

2021-04-03 11:44 UTC, ArturKovacs commented
Hey, thanks for the contribution!

Which compositor/desktop environment is this expected to work on? I tried with a KDE session and it failed

2021-04-03 12:54 UTC, xanderio commented
This protocol is from wlroots. So every compositor based on this will work e.g. sway, hikari.

https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-data-control-unstable-v1.xml

2021-04-03 17:09 UTC, ArturKovacs requested changes

2021-04-03 17:09 UTC, ArturKovacs commented on src/wayland_data_control_clipboard.rs
> +		opts.copy(source, MimeType::Autodetect).map_err(map_copy_error)?;
It seems to me that using `MimeType::Text` is more desirable here.

2021-04-03 17:09 UTC, ArturKovacs commented on src/wayland_data_control_clipboard.rs
> +		let result = get_contents(ClipboardType::Regular, Seat::Unspecified, MimeType::Any);
I'm pretty sure this should use `MimeType::Specific("image/png")`.

2021-04-03 17:09 UTC, ArturKovacs commented on src/wayland_data_control_clipboard.rs
> +		}
Considering that this is used from both x11 and wayland, and that this only depends on the standard library, I think this should be moved to `common.rs`.

2021-04-03 17:09 UTC, ArturKovacs commented on src/wayland_data_control_clipboard.rs
> +		// `output` before we `try_unwrap()`
The "Rust impl" prefix should be removed from here. I only used it in the x11 implementation because many comments there are from the original C++ implementation.

2021-04-03 21:03 UTC, xanderio commented on src/wayland_data_control_clipboard.rs
> +fn map_copy_error(error: wl_clipboard_rs::copy::Error) -> Error {
I would love to do so, but `wl-clipboard-rs::copy::Error` dos not implement `std::error::Error`

2021-04-03 21:50 UTC, ArturKovacs commented on src/wayland_data_control_clipboard.rs
> +fn map_copy_error(error: wl_clipboard_rs::copy::Error) -> Error {
Oh. And what about `Display` like this
```rust
fn into_unknown<E: std::fmt::Display>(error: E) -> Error {
    Error::Unknown {
        description: format!("{}", error),
    }
}
```

2021-04-04 14:40 UTC, xanderio commented
As i don't have a X11 setup, i wasn't able to verify the changes to x11_clipboard.rs

2021-04-04 15:59 UTC, xanderio commented on src/wayland_data_control_clipboard.rs
> +		let result = get_contents(ClipboardType::Regular, Seat::Unspecified, MimeType::Any);
Im not sure if we should just allow PNG image to be fetched from the clipboard. What about an JPEG image in the clipboard?

2021-04-05 13:16 UTC, ArturKovacs requested changes
I also just realized that the way this is currently structured, there's no way to build `arboard` in a way that it supports *both* X11 and Wayland, but this should be allowed because most developers will want to make software be compatible with X11.

So there should be a struct which wraps around both the X11 and the Wayland clipboard and decides at runtime which one to use. This struct could be defined in the `linux_common.rs` module which I mention in one of my comments in this review.

2021-04-05 13:16 UTC, ArturKovacs commented on src/wayland_data_control_clipboard.rs
> +		let result = get_contents(ClipboardType::Regular, Seat::Unspecified, MimeType::Any);
The problem here is that a clipboard may store a single "object" in multiple formats. For example if you copy some SVG elements using your SVG editor, it might place both `image/svg` and `image/png` onto the clipboard. The `get_contents` function only retrieves one of these items, so if we are unlucky we would get the SVG which we can't decode into an pixel array.

Considering that `image/png` is the de facto image format for the clipboard on Linux, we should ask specifically for `image/png`. (Also note that arboard only supports PNG currently. See the image dependency in `Cargo.toml`)

2021-04-05 14:22 UTC, ArturKovacs commented
Considering that the changes I'm asking for are not trivial, and that I have a somewhat specific idea about how it should be done, if you'd like I can just merge this PR into a topic branch, and I can finish the rest of the work myself. But if you want to complete this, that's totally fine too.

2021-04-05 14:36 UTC, xanderio commented
Sure go ahead. If i can be of any other help to this progress please let me know. :)

2021-04-05 14:47 UTC, ArturKovacs commented
Awesome. I created an `add-wayland` branch. Just re-target this PR to that branch, and I'll take care of the rest. 🙂

2021-04-05 14:49 UTC, merged

2021-04-05 14:49 UTC, ArturKovacs commented
Thanks again!