Support selecting which linux clipboard we operate on.
ArturKovacs/arboard pull request #17
Opened 2021-06-14 12:19 UTC by mathieulj

On linux, we have multiple different clipboards (3 on X11, 2 on Wayland). This PR exposes the ability to operate on the alternate clipboards without altering the cross platform API (utilizing an extension trait).

I look forward to hearing what you think of these changes :grinning:.

Closes #16

2021-06-18 07:50 UTC, ArturKovacs commented
Hey thanks for the PR! I took a quick look at it and it looks really good, but currently I have quite a few things to do, so I'm going to take a deeper look into it and try it out myself a bit later.

2021-07-04 09:21 UTC, ArturKovacs requested changes
All-in-all this is an awesome PR, thank you. I did request a few changes, but I'm eager to merge this.

2021-07-04 09:21 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +
Thanks for removing the partially written comment. I don't know who could have left that there, but I guess that

2021-07-04 09:21 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +	}
This could just invoke `self.set_text_with_clipboard(message, LinuxClipboardKind::Clipboard)` to avoid code duplication. You used this pattern at other places so I guess you just forgot to do it here.

2021-07-07 13:18 UTC, mathieulj commented on src/wayland_data_control_clipboard.rs
> +				return Err(Error::ContentNotAvailable);
I initially hesitated to create such an error variant because it would only be triggered on linux but I find it much cleaner this way if your comfortable having it in the generic API.

2021-07-07 13:23 UTC, mathieulj commented on src/wayland_data_control_clipboard.rs
>  		opts.copy(source, MimeType::Text).map_err(into_unknown)?;
Good call, I made the change.

2021-07-07 13:25 UTC, mathieulj commented on src/x11_clipboard.rs
> +		}
Yeah, IMO ether way has it's quirks. This kinda feels like abusing the match patterns but an `if` `else if` chain would feel overly verbose. Then again, I am a little weird.

2021-07-07 13:26 UTC, mathieulj commented on src/x11_clipboard.rs
> +	}
Nice catch, I did miss this opportunity.

2021-07-07 13:33 UTC, mathieulj commented
Thanks for having a review. I've applied your suggestions (which were great BTW). Let me know if you think of anything else!

2021-07-07 19:55 UTC, merged

2021-07-07 19:56 UTC, ArturKovacs commented
Thanks again for your contribution!