Make image data functionality an optional feature
ArturKovacs/arboard pull request #18
Opened 2021-07-06 03:21 UTC by dnaka91

2021-07-07 19:51 UTC, ArturKovacs requested changes
Thanks, great PR. The only thing really is just making the feature a default and the things that come with that.

2021-07-07 19:51 UTC, ArturKovacs commented on Cargo.toml
> +image-data = ["core-graphics", "image", "winapi/minwindef", "winapi/wingdi", "winapi/winnt"]
As you suggested, let's make `image-data` a default feature.

2021-07-07 19:51 UTC, ArturKovacs commented on Cargo.toml
> +required-features = ["image-data"]
When `image-data` becomes a default feature, I believe these won't be needed.

2021-07-07 19:51 UTC, ArturKovacs commented on .github/workflows/test.yml
> +          args: --verbose --features wayland-data-control
When `image-data` becomes a default, these should be adjusted so that they are called with `--no-default-features`

2021-07-07 19:51 UTC, ArturKovacs commented on .github/workflows/test.yml
> +          command: test --all-features
Same here as above: `--no-default-features`

2021-07-09 07:12 UTC, dnaka91 commented on .github/workflows/test.yml
> +          args: --verbose --features wayland-data-control
There is a nice tool [cargo-hack](https://github.com/taiki-e/cargo-hack) for it that conveniently runs commands on all combinations of the crate and avoids missing out combinations in the future.

How do you feel about using it here? I use it myself quite often, just in the CI it might take a bit of extra time to compile it first.

2021-07-09 07:13 UTC, dnaka91 commented on Cargo.toml
> +required-features = ["image-data"]
These would still be needed as you can use `--no-default-features` and then they would fail to compile.

2021-07-12 16:44 UTC, ArturKovacs commented on Cargo.toml
> +required-features = ["image-data"]
Ah, gotcha!

2021-07-12 16:44 UTC, ArturKovacs commented on .github/workflows/test.yml
> +          args: --verbose --features wayland-data-control
Let's just keep it manual for now.

2021-07-12 17:58 UTC, merged

2021-07-12 17:59 UTC, ArturKovacs commented
Thanks for the contribution!