Replace `xcb` with `x11rb`
ArturKovacs/arboard pull request #9
Opened 2021-03-08 09:09 UTC by daxpedda

I really only did a 1:1 translation. I believe `x11rb` can do much better here. I am still very new to X11, currently experimenting with a better solution, but this is totally mergable.

`libc` was dropped in the process.
I did a number of very small improvements.
There are a number of functions here that return an anunhandled `Result`, seeing that these errors were unhandled before I left everything as it was, I will fix it if I manage to improve things.

Fixes #8.

2021-03-08 09:10 UTC, daxpedda commented on src/x11_clipboard.rs
> +		})?;
Instead of gettings the first screen, we are getting the correct screen passed down from `connect`.

2021-03-08 09:10 UTC, daxpedda commented on src/x11_clipboard.rs
> +			x11rb::COPY_DEPTH_FROM_PARENT,
Instead of `0` depth, we copy from parent.

2021-03-08 12:21 UTC, daxpedda commented
@ArturKovacs I don't plan to improve this any further unless necessary.
Long-term I believe we should try to adopt this code: https://github.com/hecrj/window_clipboard/blob/master/x11/src/lib.rs

2021-03-08 19:11 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +			x11rb::COPY_DEPTH_FROM_PARENT,
I'm wondering why is this better, when the window remains hidden, and is never drawn on.

2021-03-08 19:11 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +}
This is awesome!

2021-03-08 19:11 UTC, ArturKovacs commented on src/x11_clipboard.rs
> -use libc;
No `libc`, yaay!

2021-03-08 19:47 UTC, ArturKovacs requested changes

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +		);
This error should be propagated by something like this:
```rust
).map_err(|e| Error::Unknown { description: format!("{}", e) })?;
```

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +		);
Let's bring in the `log` crate and use either `log::error!` or `log::warn!` here, to log the error message, but leave it at that. I don't know what it means for us if this fails so I leave it up to you to decide which one you use.

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
>  				shared!().conn.as_ref().unwrap().flush();
These should be ignored. (Definitely *not* unwrapped because this is called from a `drop`, and we probably don't want to panic while potentially another panic is happening)
```suggestion
				let _ = shared!().conn.as_ref().unwrap().destroy_window(window);
				let _ = shared!().conn.as_ref().unwrap().flush();
```

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +		shared.conn.as_ref().unwrap().change_property32(
Just like before, let's use either `log::error!` or `log::warn!` here.

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +					);
Use `log::error!` or `log::warn!` here as well.

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
>  	shared.conn.as_ref().unwrap().flush();
Just as before, `log::error!` or `log::warn!`.

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
>  			);
`log:error!` or `log::warn!`

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
>  			locked.shared.conn.as_ref().unwrap().flush();
And `log:error!` or `log::warn!` here as well.

2021-03-08 19:47 UTC, ArturKovacs commented on src/x11_clipboard.rs
> +	shared.conn.as_ref().unwrap().send_event(false, requestor, EventMask::NO_EVENT, notify);
And `log::error!` or `log::warn!` here as well.

2021-03-08 20:23 UTC, daxpedda commented on src/x11_clipboard.rs
> +			x11rb::COPY_DEPTH_FROM_PARENT,
This makes a lot of sense, I misunderstood what creating the window here does.

2021-03-08 20:25 UTC, daxpedda commented on src/x11_clipboard.rs
> +		);
Done.

2021-03-08 20:28 UTC, daxpedda commented on src/x11_clipboard.rs
> +		);
Done. I just added `log::error!("{}", e)`, let me know if you want to add any more text to it.

2021-03-08 20:29 UTC, daxpedda commented on src/x11_clipboard.rs
>  				shared!().conn.as_ref().unwrap().flush();
Done.

2021-03-08 20:32 UTC, daxpedda commented on src/x11_clipboard.rs
> +		shared.conn.as_ref().unwrap().change_property32(
Done.

2021-03-08 20:32 UTC, daxpedda commented on src/x11_clipboard.rs
> +					);
Done.

2021-03-08 20:33 UTC, daxpedda commented on src/x11_clipboard.rs
>  	shared.conn.as_ref().unwrap().flush();
Done.

2021-03-08 20:34 UTC, daxpedda commented on src/x11_clipboard.rs
>  			);
Done.

2021-03-08 20:34 UTC, daxpedda commented on src/x11_clipboard.rs
>  			locked.shared.conn.as_ref().unwrap().flush();
Done.

2021-03-08 20:35 UTC, daxpedda commented on src/x11_clipboard.rs
> +	shared.conn.as_ref().unwrap().send_event(false, requestor, EventMask::NO_EVENT, notify);
Done.

2021-03-08 21:28 UTC, merged

2021-03-08 21:35 UTC, ArturKovacs commented
Awesome, thanks a lot! Oh and I almost forgot: yeah I also thought about significantly refactoring this, especially because how the locking and the condvar is used. It feels messy, but it would require me to gain a much better understanding of how this protocl works, and there are other things that keep me busy so I don't know if I'll ever be able to do this.

2021-03-08 22:16 UTC, daxpedda commented
No worries, I am in the same position.
I believe there is some potential to collaborate with @hecrj through [window_clipboard](https://crates.io/crates/window_clipboard), but he does seem quiet busy with other things too.

2021-03-09 08:27 UTC, ArturKovacs commented
That's a great idea! I would be up for some collaboration. There is a tough question though: which repo do we collaborate on? I would like to keep improving this, and I'm guessing @hecrj would like to stick to `window_clipboard`. Although it would probably be better for the ecosystem to reduce the amount of competing solutions for the exact same thing. I'm open to suggestions.

Side note: I'd be happy to add support for creating the clipboard from a window.

2021-03-09 08:31 UTC, daxpedda commented
I obviously can't speak for @hecrj or his project, but I know that the two projects divert in their scope.
But I agree, ideally we have only one implementation, preferably with the wider scope of course.

I think it's best if we wait for an answer from @hecrj or you contact him directly. I am also up for contributing and maintaining, as long as somebody helps with the X11 implementation :smile:.

2021-03-10 00:06 UTC, hecrj commented
Hey! I didn't know about this crate!

I started [`window_clipboard`] as an experiment and to satisfy any use cases that [`iced`] may have.

I am open to collaborate. This crate seems to be further ahead than [`window_clipboard`], so maybe I should simply ditch that and help here.

When it comes to [`iced`], I am concerned with the blocking time of the read operations. I started [`window_clipboard`] because the other available clipboard crates waited a long time while polling, causing dropped frames. Although I believe a proper solution would involve a proper concurrent architecture for the widget logic in [`iced`].

[`iced`]: https://github.com/hecrj/iced

2021-03-10 21:17 UTC, daxpedda commented
> Although I believe a proper solution would involve a proper concurrent architecture for the widget logic in [`iced`](https://github.com/hecrj/iced) (so they can read the clipboard without blocking everything else).

How would that work, do you mean an `async` interface?

2021-03-14 12:43 UTC, ArturKovacs commented
@hecrj I looked a little bit into your implementation and it seems to be much cleaner than the one here. There is something that I don't understand though. You have a separate window for reading and writing, and if I'm not mistaken you only take out events form your read event queue when a clipboard read happens. Is this okay to do? Shouldn't the event queue be polled constantly to avoid the queue growing too large?

My understanding on X programming is very limited so that's why I don't understand if/why this is okay.